# This is a basic workflow to help you get started with Actions

name: Main

on:
  workflow_dispatch:

jobs:
  reused-1:
    uses: ./.github/workflows/reused.yml
  
  reused-2:
    uses: ./.github/workflows/reused-2.yml

  build-finally:
    runs-on: ubuntu-latest
    needs: ['reused-1', 'reused-2']
    steps:
      - name: Download r1
        uses: actions/download-artifact@v4
        with:
          name: r1
          path: 'outputs/'

      - name: Download r2
        uses: actions/download-artifact@v4
        with:
          name: r2
          path: 'outputs/'

      - name: Download r3
        uses: actions/download-artifact@v4
        with:
          name: r3
          path: 'outputs/'

      - name: Show me result
        run: |
          ls -R 
          
