# This is a basic workflow to help you get started with Actions

name: Main

on:
  workflow_dispatch:

jobs:
  reused-1:
    uses: ./.github/workflows/reused.yml
  
  reused-2:
    uses: ./.github/workflows/reused-2.yml

  build-finally:
    runs-on: ubuntu-latest
    needs: ['reused-1', 'reused-2']
    steps:
      - name: Download All
        uses: dawidd6/action-download-artifact@v6
        with:
          path: 'outputs/'
          run_id: ${{ github.run_id }}

      - name: Show me result
        run: |
          ls -R 
          
