# This is a basic workflow to help you get started with Actions

name: Main

on:
  workflow_dispatch:

jobs:
  reused-1:
    uses: ./.github/workflows/reused.yml
  
  reused-2:
    uses: ./.github/workflows/reused-2.yml

  build-finally:
    runs-on: ubuntu-latest
    needs: ['reused-1', 'reused-2']
    steps:
      - name: Download r1
        uses: dawidd6/action-download-artifact@v6
        with:
          name: r1
          run_id: ${{ github.event.workflow_run.id }}
          path: 'outputs/'
          
      - name: Download r2
        uses: dawidd6/action-download-artifact@v6
        with:
          name: r2
          run_id: ${{ github.event.workflow_run.id }}
          path: 'outputs/'
          
      - name: Download r3
        uses: dawidd6/action-download-artifact@v6
        with:
          name: r3
          run_id: ${{ github.event.workflow_run.id }}
          path: 'outputs/'

      - name: Show me result
        run: |
          ls -R 
          
