name: Reused-1

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate result
        run: |
          echo 1 > r1.txt
          echo 2 > r2.txt
          
      - name: Upload Artifact (r1)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: r1
          path: ${{github.workspace}}/r1

      - name: Upload Artifact (r2)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: r2
          path: ${{github.workspace}}/r2
